language: node_js
node_js:
- '0.12'
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./kickstart.sh
script: gulp travis:angularjs && gulp travis:react
