language: node_js
node_js:
  - "6.1"
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i
- webdriver-manager update
script: npm run tests
